name: Dev - Test

on:
  push:
    branches:
      - dev

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  package:
    name: Build and Check Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: hynek/build-and-inspect-python-package@main

  test:
    needs: [package]

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: ["3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest]
        include:
          - python: "3.11"
            tox_env: "py311-pytest8"
          - python: "3.12"
            tox_env: "py312-pytest8"
          - python: "3.13"
            tox_env: "py313-pytest8"
    steps:
    - uses: actions/checkout@main

    - name: Download Package
      uses: actions/download-artifact@main
      with:
        name: Packages
        path: dist

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install tox
      run: pip install tox

    - name: Test
      shell: bash
      run: tox run -e ${{ matrix.tox_env }}